# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-09 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('collegeId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('collegeName', models.CharField(max_length=16)),
                ('collegeArea', models.CharField(max_length=10)),
                ('collegeGrade', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('phoneId', models.IntegerField(primary_key=True, serialize=False)),
                ('phoneMode', models.CharField(max_length=30)),
                ('phoneDetail', models.CharField(max_length=100)),
                ('phonePrice', models.IntegerField()),
                ('area', models.CharField(max_length=10)),
                ('phoneImgUrl', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('phoneNum', models.BigIntegerField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=10)),
                ('passWrod', models.CharField(max_length=16)),
            ],
        ),
    ]
