# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-16 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20181016_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='phoneCharacter',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='phoneModel',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='phonePrice',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
