# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-25 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_phone_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phoneMode',
            field=models.CharField(max_length=40),
        ),
    ]
